language: ruby
os:
  - linux
  - osx
install: |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get update >/dev/null
    sudo apt-get install -y zsh git make curl
  else
    softwareupdate --all --install --force
    brew update >/dev/null
    brew install zsh
  fi
script: make ci
notifications:
  email: false
