tap "getantibody/tap"
tap "go-delve/delve"
tap "golangci/tap"
tap "goreleaser/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
tap "robscott/tap"
# The fastest shell plugin manager
brew "antibody"
# Shell extension to jump to frequently used directories
brew "autojump"
# Cryptography and SSL/TLS Toolkit
brew "openssl@1.1"
# Official Amazon AWS command-line interface
brew "awscli"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Increase version numbers with SemVer terms
brew "bumpversion"
# Utility that creates projects from templates
brew "cookiecutter"
# Load/unload environment variables based on $PWD
brew "direnv"
# Lightweight DNS forwarder and DHCP server
brew "dnsmasq", restart_service: true
# Git extension for versioning large files
brew "git-lfs"
# Alternative to top/htop
brew "glances"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Open-source build automation tool based on the Groovy and Kotlin DSL
brew "gradle"
# Smarter Dockerfile linter to validate best practices
brew "hadolint"
# The Kubernetes package manager
brew "helm"
# The Kubernetes package manager
brew "helm@2"
# Manage your Java environment
brew "jenv"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Run local Kubernetes cluster in Docker
brew "kind"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Tool that can switch between kubectl contexts easily and create aliases
brew "kubectx"
# Library for database change tracking
brew "liquibase"
# Java-based project management
brew "maven"
# Platform built on V8 to build network applications
brew "node"
# SSL/TLS VPN implementing OSI layer 2 or 3 secure network extension
brew "openvpn"
# CLI for Postgres with auto-completion and syntax highlighting
brew "pgcli"
# Object-relational database system
brew "postgresql"
# Password generator
brew "pwgen"
# Build tool for Scala projects
brew "sbt"
# JVM-based programming language
brew "scala"
# Build applications with serverless architectures
brew "serverless"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Autoformat shell script source code
brew "shfmt"
# Tail multiple Kubernetes pods & their containers
brew "stern"
# User interface to the TELNET protocol
brew "telnet"
# Tool to build, change, and version infrastructure
brew "terraform"
# Thin wrapper for Terraform e.g. for locking state
brew "terragrunt"
# Linter for Terraform files
brew "tflint"
# Code-search similar to ack
brew "the_silver_searcher"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# Process YAML documents from the CLI
brew "yq"
# High-performance, schema-free, document-oriented database
brew "mongodb/brew/mongodb-community@3.6"
# kube-capacity provides an overview of the resource requests, limits, and utilization in a Kubernetes cluster
brew "robscott/tap/kube-capacity"
cask "1password"
cask "1password-cli"
cask "adoptopenjdk"
cask "adoptopenjdk8"
cask "authy"
cask "brave-browser"
cask "chromium"
cask "datagrip"
cask "docker"
cask "gitkraken"
cask "google-cloud-sdk"
cask "iterm2"
cask "java11"
cask "min"
cask "notion"
cask "numi"
cask "postman"
cask "skype"
cask "slack"
cask "spotify"
cask "telegram"
cask "tunnelblick"
cask "visual-studio-code"
cask "whatsapp"
