tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
tap "robscott/tap"
# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Shell extension to jump to frequently used directories
brew "autojump"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Core application library for C
brew "glib"
# Utility that creates projects from templates
brew "cookiecutter"
# Top-like interface for container metrics
brew "ctop"
# Load/unload environment variables based on $PWD
brew "direnv"
# Lightweight DNS forwarder and DHCP server
brew "dnsmasq"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Find files with SQL-like queries
brew "fselect"
# Interpreter for PostScript and PDF
brew "ghostscript"
# Git extension for versioning large files
brew "git-lfs"
# Blazing fast terminal-ui for git written in rust
brew "gitui"
# Alternative to top/htop
brew "glances"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# OpenType text shaping engine
brew "harfbuzz"
# Framework for layout and rendering of i18n text
brew "pango"
# Library to render SVG files using Cairo
brew "librsvg"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Smarter Dockerfile linter to validate best practices
brew "hadolint"
# Kubernetes package manager
brew "helm"
# Improved top (interactive process viewer)
brew "htop"
# Configurable static site generator
brew "hugo"
# Command-line benchmarking tool
brew "hyperfine"
# Platform built on V8 to build network applications
brew "node"
# High precision scientific calculator with support for physical units
brew "insect"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Kubernetes CLI To Manage Your Clusters In Style!
brew "k9s"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Tool that can switch between kubectl contexts easily and create aliases
brew "kubectx"
# Clone of ls with colorful output, file type icons, and more
brew "lsd"
# Utility for directing compilation
brew "make"
# Fast, highly customisable system info script
brew "neofetch"
# Port scanning utility for large networks
brew "nmap"
# Optimized BLAS library
brew "openblas"
# Development kit for the Java programming language
brew "openjdk@11"
# CLI for Postgres with auto-completion and syntax highlighting
brew "pgcli"
# Protocol buffers (Google's data interchange format)
brew "protobuf"
# Password generator
brew "pwgen"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Perl-powered file rename script with many helpful built-ins
brew "rename"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Safe, concurrent, practical language
brew "rust"
# Build applications with serverless architectures
brew "serverless"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Autoformat shell script source code
brew "shfmt"
# Tail multiple Kubernetes pods & their containers
brew "stern"
# Generate clients, server stubs, and docs from an OpenAPI spec
brew "swagger-codegen"
# User interface to the TELNET protocol
brew "telnet"
# Tool to build, change, and version infrastructure
brew "terraform"
# Thin wrapper for Terraform e.g. for locking state
brew "terragrunt"
# Linter for Terraform files
brew "tflint"
# Code-search similar to ack
brew "the_silver_searcher"
# Programmatically correct mistyped console commands
brew "thefuck"
# Terminal multiplexer
brew "tmux"
# Command-line client for Travis CI
brew "travis"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Command-line interface for Vercel
brew "vercel-cli"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# kube-capacity provides an overview of the resource requests, limits, and utilization in a Kubernetes cluster
brew "robscott/tap/kube-capacity"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Cross platform SQL editor and database management app
cask "beekeeper-studio"
# Voice and text chat software
cask "discord"
# App to build and share containerized applications and microservices
cask "docker"
# Developer targeted fonts with a high number of glyphs
cask "font-meslo-lg-nerd-font"
# Git client focusing on productivity
cask "gitkraken"
# Web browser
cask "google-chrome"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "google-cloud-sdk"
# Client for the Google Drive storage service
cask "google-drive"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# GPU-based terminal emulator
cask "kitty"
# Software for Logitech devices
cask "logitech-options"
# App to write, plan, collaborate, and get organized
cask "notion"
# Replacement for Docker Desktop
cask "orbstack"
# Collaboration platform for API development
cask "postman"
# Archive manager for data compression and backups
cask "rar"
# Control your tools with a few keystrokes
cask "raycast"
# Strongdm client
cask "sdm"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# Messaging app with a focus on speed and security
cask "telegram"
# Open-source code editor
cask "visual-studio-code"
# Desktop client for WhatsApp
cask "whatsapp"
