#!/usr/bin/env zsh
#
# Run all dotfiles installers.
set -e

cd "$(dirname "$0")/.." || exit
DOTFILES_ROOT=$(pwd -P)
# shellcheck source=tools
. "$DOTFILES_ROOT/scripts/tools"
cd "$DOTFILES_ROOT"

CONFIG="$DOTFILES_ROOT/install.conf.yaml"
DOTBOT_DIR="$DOTFILES_ROOT/dotbot"

info "Upgrading dotfiles. Today is $(date)"

info "git update"
git pull --quiet >/dev/null 2>&1 || true

git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${DOTBOT_DIR}/bin/dotbot" -v -d "${DOTFILES_ROOT}" -c "${CONFIG}" "${@}"

info "Find the installers and run them iteratively"
for installer in "${DOTFILES_ROOT}"/**/install.sh; do
    info "Run ${installer}..."
    sh -c "$installer"
    success "${installer}"
done

info "Find the configurators and run them iteratively"
for configurator in "${DOTFILES_ROOT}"/**/configure.sh; do
    info "Run ${configurator}..."
    sh -c "$configurator"
    success "${configurator}"
done

info "Registering last update"

git config --global dotfiles.lastupdate "$(date +%Y-%m-%d-%H:%M)"
