#!/usr/bin/env sh
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
# shellcheck source=tools
. "$DOTFILES_ROOT/scripts/tools"

set -e

echo ''


info "Installing dotfiles"
if ./scripts/apply; then
    success "All installed"
else
    fail "Error installing dotfiles"
fi


echo ''
success '  Dotfiles configured!'
