#!/bin/sh
#
# Run all dotfiles installers.
set -e

DOTFILES_ROOT=$(realpath "$(dirname "$0")/..")
# shellcheck source=tools
. "$DOTFILES_ROOT/scripts/tools"
cd "$DOTFILES_ROOT"

info "Find the installers and run them iteratively"
git ls-tree --name-only -r HEAD | grep install.sh | while read -r installer; do
    info "Run ${installer}..."
    sh -c "$installer"
    success "${installer}"
done
