#!/bin/sh
#
# link dotfiles from repo to home

cd "$(dirname "$0")/.." || exit
DOTFILES_ROOT=$(pwd -P)
# shellcheck source=tools
. "$DOTFILES_ROOT/scripts/tools"

link_dotfiles() {
    info 'Linking dotfiles'
    find -H "$DOTFILES_ROOT" -maxdepth 3 -name '*.symlink' -not -path '*.git*' |
        while read -r src; do
            dst="$HOME/.$(basename "${src%.*}")"
            link_file "$src" "$dst"
        done
}

link_dotfiles
