#!/bin/zsh
set -e

# Link to ~ and cd to it
cd ..
cp -rf dotfiles ~/.dotfiles
cd ~/.dotfiles

# Setup git credentials
echo "setup git fake user/email"
git config --global user.name "dotfiles demo"
git config --global user.email "dotfiles@demo.com"

# Bootstrap the mighty
echo "boostraping..."
./scripts/bootstrap

# Load zshrc and check if antibody is working
echo "sourcing ~/.zshrc"
# shellcheck disable=SC1090
source ~/.zshrc || true

test "$(antibody list | wc -l)" -gt 4 || {
	echo "expecting 4+ bundles loaded" >&2
	exit 1
}

test -s ~/.zcompdump || {
	echo "zcompdump file is empty" >&2
	exit 1
}

# Check if a random plugin is working (meaning that the bundles were loaded)
ports ls
