#!/usr/bin/env sh
#
# common functions to use in scripts

# Color constants
RED='\033[0;31m'
GREEN='\033[00;32m'
YELLOW='\033[0;33m'
BLUE='\033[00;34m'
RESET='\033[0m'

LOG_DEPTH=${LOG_DEPTH:-0}
LOG_INDENT_SIZE=${LOG_INDENT_SIZE:-4}

log_prefix() {
    printf "%*s" "$((LOG_DEPTH * LOG_INDENT_SIZE))" ""
}

info() {
    # shellcheck disable=SC2059
    printf "\r%s[ ${BLUE}..${RESET} ] $1\n" "$(log_prefix)"
}

user() {
    # shellcheck disable=SC2059
    printf "\r%s[ ${YELLOW}??${RESET} ] $1\n" "$(log_prefix)"
}

success() {
    # shellcheck disable=SC2059
    printf "\r\033[2K%s[ ${GREEN}OK${RESET} ] $1\n" "$(log_prefix)"
}

warning() {
    # shellcheck disable=SC2059
    printf "\r%s[ ${YELLOW}!!${RESET} ] $1\n" "$(log_prefix)"
}

fail() {
    # shellcheck disable=SC2059
    printf "\r\033[2K%s[${RED}FAIL${RESET}] $1\n" "$(log_prefix)"
    echo ''
    exit
}

validate_semver() {
    version=$1
    if ! echo "$version" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\-]+)?(\+[a-zA-Z0-9\-]+)?$'; then
        fail "Invalid semantic version format: $version. Expected format: X.Y.Z[-prerelease][+build] (e.g., 1.0.0, 1.0.0-beta.1, 1.0.0+20230101)" >&2
    fi
}
