#!/bin/sh
#
# Run all dotfiles updaters.
set -e

DOTFILES_ROOT=$(realpath "$(dirname "$0")/..")
# shellcheck source=tools
. "$DOTFILES_ROOT/scripts/tools"

info "Updating dotfiles. The las version will be dumped in the repo"
cd "$DOTFILES_ROOT"

info "Find the updaters and run them iteratively"
git ls-tree --name-only -r HEAD | grep update.sh | while read -r updater; do
    info "Run ${updater}..."
    sh -c "$updater"
    success "${updater}"
done
