#!/usr/bin/env sh
#
# Run all dotfiles updaters.
set -e

cd "$(dirname "$0")/.." || exit
DOTFILES_ROOT=$(pwd -P)
# shellcheck source=tools
. "$DOTFILES_ROOT/scripts/tools"

info "Updating dotfiles. The las version will be dumped in the repo"
cd "$DOTFILES_ROOT"

info "Find the updaters and run them iteratively"
for updater in "${DOTFILES_ROOT}"/**/update.sh; do
    info "Run ${updater}..."
    sh -c "$updater"
    success "${updater}"
done
