#!/bin/sh
#
# dotfiles-update
#
# `dotfiles-update` handles installation, updates, things like that. Run it
# periodically to make sure you're on the latest and greatest.
export DOTFILES="$HOME/.dotfiles"
cd "$DOTFILES" || exit 1

# shellcheck source=tools
. "$DOTFILES/scripts/tools"

# fixes PATH (we could be running from the crontab)
PATH="$(command -p getconf PATH):/usr/local/bin"

info "Upgrading dotfiles. Today is $(date)"

# ssh would not work under cron, add a https one
info "Setting up update channel"
git remote add updates https://github.com/pablosjv/dotfiles.git 2>/dev/null

# Update repo
info "git update"
git pull

# Linking files again
info "Linking with $DOTFILES/scripts/link"
"$DOTFILES/scripts/link"

# Run all installs
info "Installing with $DOTFILES/scripts/install"
"$DOTFILES/scripts/install"

# Run all configurations
info "Configuring with $DOTFILES/scripts/configure"
"$DOTFILES/scripts/configure"

if command -v antibody >/dev/null 2>&1; then
    info "antibody update"
    antibody update
fi

info "registering last update"
git config --global dotfiles.lastupdate "$(date +%Y-%m-%d-%H:%M)"
