# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: "0 0 1 * *"

  workflow_dispatch:

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare linux runner
        run: |
          sudo apt-get update >/dev/null
          sudo apt-get install -y zsh git make curl

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: make ci

  macos-build:
    runs-on: macos-latest

    steps:
      - name: Prepare macOS runner
        uses: paulz/prepare-macos@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: make ci
